CREATE TABLE events (
  id UUID PRIMARY KEY,
  title TEXT NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  min_price INTEGER NOT NULL,
  max_price INTEGER NOT NULL
);

